name: digimobil_new
description: "Digital Salon Mobile App - User Only"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # State Management
  provider: ^6.0.5
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # UI & Images
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  file_picker: ^8.0.0+1
  image_picker: ^1.0.4
  image_cropper: ^8.0.1
  image: ^4.2.0
  photo_manager: ^3.2.0
  video_player: ^2.8.1
  mobile_scanner: ^5.0.0
  camera: ^0.10.5+5
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  package_info_plus: ^9.0.0
  
  # File Download
  gal: ^2.0.2
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Deep Links
  app_links: ^6.3.1
  
  # Background Tasks & Notifications
  flutter_local_notifications: ^17.0.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.4
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.5
  
  # OAuth & Social Login
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  
  # WebView for reCAPTCHA
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/terms.txt

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true